import { PRSummary } from '../types';

/**
 * Format PR summary as markdown comment
 */
export function formatSummaryAsMarkdown(summary: PRSummary): string {
  const sections: string[] = [
    '## 🤖 AI-Generated PR Summary',
    '',
    '### What Changed',
    summary.what,
    '',
    '### Why',
    summary.why,
    '',
    '### Impact',
    summary.impact,
  ];

  if (summary.notes) {
    sections.push('', '### Additional Notes', summary.notes);
  }

  sections.push(
    '',
    '---',
    '_This summary was automatically generated by AI. Please review for accuracy._'
  );

  return sections.join('\n');
}

/**
 * Format [NEEDS_INPUT] message for user
 */
export function formatNeedsInputMessage(): string {
  return `## 🤖 AI-Generated PR Summary

⚠️ **Unable to generate summary - insufficient context**

This PR doesn't have enough information for the AI to generate a meaningful summary.
To get an AI-generated summary, please:

1. Add a descriptive PR description explaining what this PR does and why
2. Ensure commit messages are clear and descriptive
3. Make sure the PR includes actual code changes (not just configuration or trivial updates)

Once you've added more context, trigger a new summary by:
- Pushing a new commit
- Closing and reopening the PR
- Adding a comment with \`@bot summarize\` (if enabled)

---
_This is an automated message from the PR Summarizer Bot._`;
}

/**
 * Truncate text to max length with ellipsis
 */
export function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) {
    return text;
  }
  return text.substring(0, maxLength - 3) + '...';
}

/**
 * Escape markdown special characters
 */
export function escapeMarkdown(text: string): string {
  return text.replace(/([\\`*_{}[\]()#+\-.!|])/g, '\\$1');
}
